// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_QgZEJk0We4xpL42htIe16Ob7Ja81t48',
    appId: '1:815304788180:web:ddf79a39bcb0856d0bd341',
    messagingSenderId: '815304788180',
    projectId: 'nileshipping-aa924',
    authDomain: 'nileshipping-aa924.firebaseapp.com',
    storageBucket: 'nileshipping-aa924.appspot.com',
    measurementId: 'G-K22HTGZ6FE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0LnHi35rcZF3UoxI5fgCvCloZ0D-sGvE',
    appId: '1:815304788180:android:1c8e530edb8ebf2a0bd341',
    messagingSenderId: '815304788180',
    projectId: 'nileshipping-aa924',
    storageBucket: 'nileshipping-aa924.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZ3P4M4GxnS4A5BqXeoKMuynDtR1wPBCs',
    appId: '1:815304788180:ios:e0ddf93dd87c139f0bd341',
    messagingSenderId: '815304788180',
    projectId: 'nileshipping-aa924',
    storageBucket: 'nileshipping-aa924.appspot.com',
    iosClientId: '815304788180-jd3euoljtosd2pl2a8e2ep9gba50jbp3.apps.googleusercontent.com',
    iosBundleId: 'com.example.nileShipping',
  );
}
